# Generated by Django 3.1.4 on 2021-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210331_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous_author',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
