# Generated by Django 3.1.4 on 2021-03-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_anonymous_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous_author',
        ),
    ]
